# Generated by Django 4.2.7 on 2024-04-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0003_kruzok_student_kruzok'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kruzok',
            options={'ordering': ['nazov'], 'verbose_name': 'Krúžok', 'verbose_name_plural': 'Krúžky'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['priezvisko'], 'verbose_name': 'Študent', 'verbose_name_plural': 'Študenti'},
        ),
        migrations.AlterModelOptions(
            name='trieda',
            options={'ordering': ['nazov'], 'verbose_name': 'Trieda', 'verbose_name_plural': 'Triedy'},
        ),
        migrations.AlterModelOptions(
            name='ucitel',
            options={'ordering': ['priezvisko'], 'verbose_name': 'Učiteľ', 'verbose_name_plural': 'Učitelia'},
        ),
        migrations.AddField(
            model_name='student',
            name='obec',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='psc',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='ulica',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
