# Generated by Django 4.2.7 on 2024-04-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0004_alter_kruzok_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='psc',
            field=models.CharField(max_length=6),
        ),
    ]
