# Generated by Django 4.2.7 on 2024-04-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0005_alter_student_psc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucitel',
            name='obec',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ucitel',
            name='psc',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ucitel',
            name='ulica',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
