# Generated by Django 4.2.7 on 2024-04-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0006_ucitel_obec_ucitel_psc_ucitel_ulica'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='narodenie',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
