# Generated by Django 4.2.7 on 2024-04-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0007_student_narodenie'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucitel',
            name='narodenie',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
