# Generated by Django 4.2.7 on 2024-04-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0009_alter_ucitel_narodenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='narodenie',
            field=models.DateField(blank=True, null=True),
        ),
    ]
