# Generated by Django 4.2.7 on 2023-12-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoria',
            name='nazov',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='popis',
            field=models.TextField(),
        ),
    ]
