# Generated by Django 4.2.7 on 2023-12-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_kategoria_nazov_alter_produkt_cena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='product_id',
            field=models.CharField(default=1025, max_length=20),
            preserve_default=False,
        ),
    ]
