# Generated by Django 4.2.7 on 2023-12-15 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_uzivatelia_objednavka'),
    ]

    operations = [
        migrations.AddField(
            model_name='objednavka',
            name='uzivatel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.uzivatelia'),
        ),
    ]
